print("Hello World")
print("MY name is Kullai Gergő")
lastname = input("Enter your lastname:")
firstname = input("Enter your firstname:")
age = int(input("Enter your age:"))
height = float(input("Enter your height in meters:"))

# print("Hello " + lastname+ " "+ firstname+"!") 
print(f"Hello, {lastname} {firstname}. Your age is {age}! You are a {height}m tall.")

print(type(lastname))
print(type(age))
print(type(height))
print(int(age) + 4)
print(float(height) + 0.2)